

defaults:
  - headset: unicorn
  - experiment: ssvep
  - _self_


sources: ${experiment.sources}

recording:
  subject: 1
  session: 0
  block: 0

buffer_size_seconds: 60

persister: ${experiment.persister}
persisting_mode: ${experiment.persisting_mode}
persister_workers: ${experiment.persister_workers}

#preprocessors: []
preprocessors:
  - name: 'eeg_scaler'
    scale: 1e-6
    channel_types: ['eeg']


real_time:
  enabled: True
  source_id: ${headset.source_id}
  stream_type: 'EEG'
  sfreq: ${headset.sfreq}
  channel: ${headset.target_channel}
  window_size_seconds: 5
  window_shift_seconds: 0.1
  buffer_size_seconds: 60
  bandpass:
    low_cut: 8
    high_cut: 28
  notch: 50
  target_frequencies: [8, 17]