

defaults:
  - headset: unicorn
  - _self_

sources:
  - - ${headset.source_id}
    - 'EEG'
  - - 'rsvp_markers'
    - 'MARKER'

signal_id: ${headset.source_id}
marker_id: 'rsvp_markers'
#marker_id: null

recording:
  subject: 1
  session: 0
  block: 0

buffer_size_seconds: 60

preprocessors:
  - name: 'eeg_scaler'
    scale: 1e-6
    channel_types: ['eeg']