

defaults:
  - experiment: ssvep
  - headset: unicorn
  - persistence: persistence
  - psd: scipy
  - real_time: default
  - recording: default
  - visualization: default
  - _self_

sources: ${experiment.sources}