

defaults:
  - decoders: decoders
  - experiment: demo
  - headset: demo
  - persistence: persistence
  - psd: scipy
  - real_time: default
  - recording: default
  - visualization: default
  - _self_

sources: ${experiment.sources}