

source_id: 'UN-2023.05.69'
n_channels: 17
channel_names: ['Fz', 'C3', 'Cz', 'C4', 'Pz', 'PO7', 'OZ', 'PO8', 'acc_x', 'acc_y', 'acc_z', 'gyro_x', 'gyro_y', 'gyro_z', 'battery_level', 'counter', 'valid_indicator']
channel_types: ['eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'eeg', 'misc', 'misc','misc', 'misc', 'misc', 'misc', 'misc', 'misc', 'misc']
sfreq: 250
